[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "otter-chess"
version = "0.1.0"
description = "Otter chess move prediction library API"
authors = [
    { name = "Tarun", email = "tarun@peargentlabs.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pyarrow",
    "python-chess",
    "wandb",
    "fastchess",
    "torch",
    "safetensors",
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Repository = "https://github.com/peargentlabs/otter-chess"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"otter.vocab" = ["*.json"]

[tool.pyrefly]
search_path = ["src", "scripts"]
